apiVersion: v1
kind: Service
metadata:
  name: jupyter-gpu
  labels:
    app: jupyter-gpu
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-gpu
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-gpu
      tier: frontend
  template:
    metadata:
      labels:
        app: jupyter-gpu
        tier: frontend
    spec:
      containers:
      - name: jupyter-gpu
        image:  kapplegate/bf_rapid_demo:1gpu
        ports:
        - containerPort: 8888
        - containerPort: 56001
