apiVersion: run.tanzu.vmware.com/v1alpha1      #TKG API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: marketing                       #cluster name, user defined
  namespace: departments                      #supervisor namespace
spec:
  distribution:
    version: v1.18                             #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-xsmall                 #vmclass for control plane nodes
      storageClass: vsan-default-storage-policy         #storageclass for control pl
    workers:
      count: 3                                 #number of worker nodes
      class: best-effort-xsmall                 #vmclass for worker nodes
      storageClass: vsan-default-storage-policy         #storageclass for worker nodes
  settings:
    storage:
      defaultClass: vsan-default-storage-policy
